language: node_js

node_js:
  - "6.11"

branches:
  only:
    - master

deploy:
  - provider: script
    script: NODE_ENV=production scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
