version: "3.8"

services:
  website:
    image: pietrum/${NODE_ENV:-development}/official-website:${TAG:-latest}
    build:
      context: .
      target: develop
      args:
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - ${PORT_PUBLISHED:-80}:${PORT:-8080}
    volumes:
      - ./src:/usr/src/app/src:rw
    environment:
      - NODE_ENV=${NODE_ENV:-development}
