version: "3.8"

services:
  website:
    image: pietrum/${NODE_ENV:-development}/official-website:${TAG:-latest}
    build:
      context: .
      target: develop
      args:
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./src:/usr/src/app/src:rw
    environment:
      - DOMAIN=${DOMAIN:-local.pietrum.pl}
      - NODE_ENV=${NODE_ENV:-development}
    labels:
      - "traefik.http.routers.website-pietrum.rule=Host(`${DOMAIN:-local.pietrum.pl}`) || Host(`${DOMAIN:-www.local.pietrum.pl}`)"

networks:
  default:
    external: true
    name: hxh
