version: "3.8"

services:

  website:
    container_name: pietrum-official-website
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    build: .
    image: pietrum/${NODE_ENV:-production}/official-website:${TAG:-latest}
    ports:
      - ${PORT:-80}:${PORT:-80}
    volumes:
      - ./src:/usr/src/app/src
    entrypoint:
      - npm
      - run
      - develop
