version: "3.8"

services:

  nginx:
    container_name: pietrum-nginx
    image: nginx:1.19-alpine
    ports:
      - ${PORT:-80}:80
    volumes:
      - mydata:/usr/share/nginx/html:ro
    depends_on:
      - website

  website:
    container_name: pietrum-official-website
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    build: .
    image: pietrum/${NODE_ENV:-production}/official-website:${TAG:-latest}
    volumes:
      - mydata:/usr/src/app/public
    entrypoint:
      - npm
      - start

volumes:
  mydata:
