version: "3.8"

services:
  website:
    image: pietrum/${NODE_ENV:-development}/official-website:${TAG:-latest}
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-development}
        - HOST=${HOST:-0.0.0.0}
        - PORT_TARGET=${PORT_TARGET:-3000}
        - PORT_PUBLISHED=${PORT_PUBLISHED:-80}
    ports:
      - ${PORT_PUBLISHED:-80}:${PORT_TARGET:-3000}
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: npm run develop
